[package]
name = "rust-tutorial"
version = "0.1.0"
authors = ["Mark Lee <mark2@linecorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
